# # name: "Terraform Best Practices"
# # description: "Run Terraform best practices checks"
# # inputs:
# #   directory:
# #     description: "Directory containing Terraform code"
# #     required: true
# # runs:
# #   using: "composite"
# #   steps:
# #     - name: Setup Terraform
# #       uses: hashicorp/setup-terraform@v2
# #       with:
# #         terraform_version: latest

# #     - name: Configure AWS Credentials
# #       uses: aws-actions/configure-aws-credentials@v4
# #       with:
# #         role-to-assume: arn:aws:iam::099199746132:role/github-oidc-provider-aws
# #         aws-region: us-east-1
    
# #     - name: Initialize Terraform
# #       shell: bash
# #       run: cd prod && terraform init
# #       working-directory: ${{ inputs.directory }}
    
# #     - name: Terraform Validate
# #       shell: bash
# #       run: cd prod &&  terraform validate
# #       working-directory: ${{ inputs.directory }}
    
# #     - name: Check Formatting
# #       shell: bash
# #       run: cd prod &&  terraform fmt -check
# #       working-directory: ${{ inputs.directory }}


# name: "Terraform Action"
# description: "Reusable Terraform steps for init, fmt, validate, plan, and apply."
# inputs:
#   aws_role_arn:
#     description: "AWS Role ARN to assume"
#     required: true
#   aws_region:
#     description: "AWS Region"
#     required: true
#   action:
#     description: "Terraform action to perform (init|fmt|validate|plan|apply)"
#     required: true
# outputs:
#   plan-file:
#     description: "Path to Terraform plan file"
# runs:
#   using: "composite"
#   steps:
#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v3
#       with:
#         role-to-assume: ${{ inputs.aws_role_arn }}
#         aws-region: ${{ inputs.aws_region }}

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v2
#       with:
#         terraform_version: 1.5.7

#     - name: Terraform Init
#       if: ${{ inputs.action == 'init' }}
#       run: terraform init

#     - name: Terraform Format Check
#       if: ${{ inputs.action == 'fmt' }}
#       run: terraform fmt -check -recursive

#     - name: Terraform Validate
#       if: ${{ inputs.action == 'validate' }}
#       run: terraform validate

#     - name: Terraform Plan
#       if: ${{ inputs.action

