name: "Terraform Apply"
description: "Terraform Plan Composite Action"
inputs:
  deploy:
    required: true
    description: "Desired state for the deployment. true=deploy | false=destroy"
  aws-region:
    required: true
    description: "AWS Region"
  terraform-execution-iam-role-arn:
    required: false
    description: "Terraform Execution IAM Role ARN"
  working-directory:
    required: false
    description: "Working Directory"
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      id: init
      uses: ./.github/actions/terraform-init
      with:
        aws-region: ${{ inputs.aws-region }}
        terraform-execution-iam-role-arn: ${{ inputs.terraform-execution-iam-role-arn}}
        working-directory: ${{ inputs.working-directory }}
    - name: Define Terraform Apply Command # 'terraform apply' or 'terraform destroy'
      id: tf_apply_command
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if ${{ inputs.deploy }}
        then
          echo "APPLY_COMMAND=terraform apply" >> $GITHUB_OUTPUT
        else
          echo "APPLY_COMMAND=terraform destroy" >> $GITHUB_OUTPUT
        fi
    - name: Terraform Apply
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ steps.tf_apply_command.outputs.APPLY_COMMAND }} \
          -var=maintainer=$GITHUB_USER \
          prod.tfplan -auto-approve