name: "Terraform Checks"
description: "Terraform Checks"
inputs:
  aws-region:
    required: true
    description: "AWS Region"
  terraform-execution-iam-role-arn:
    required: false
    description: "Terraform Execution IAM Role ARN"
  working-directory:
    required: false
    description: "Working Directory"
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      id: init
      uses: ./.github/actions/terraform-init
      with:
        aws-region: ${{ inputs.aws-region }}
        terraform-execution-iam-role-arn: ${{ inputs.terraform-execution-iam-role-arn}}
        working-directory: ${{ inputs.working-directory }}
    - name: Terraform Format and style
      id: fmt
      continue-on-error: false
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform fmt -check -diff -recursive
    - name: Terraform Validate
      id: validate
      continue-on-error: false
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform validate -no-color