name: "Terraform Init"
description: "Terraform Init Composite Action"
inputs:
  aws-region:
    required: true
    description: "AWS Region"
  terraform-execution-iam-role-arn:
    required: false
    description: "Terraform Execution IAM Role ARN"
  working-directory:
    required: false
    description: "Working Directory"
outputs:
  outcome:
    description: "Terraform init command outcome"
    value: ${{ steps.init.outcome }}
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.local-execution-mode == 'true' }}
      with:
        role-to-assume: ${{ inputs.terraform-execution-iam-role-arn }}
        role-session-name: terraform-execution-role
        aws-region: ${{ inputs.aws-region }}
        role-duration-seconds: 1200
    - name: Terraform Init
      id: init
      shell: bash
      run: cd prod && terraform init